config/routes.rb
Rails.application.routes.draw do
  get 'archivos/subir_archivos'
  post 'archivos/subir_archivos'
  get 'archivos/listar_archivos'
  post 'archivos/borrar_archivos'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
    }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "perfil#index"
end

app/controllers/perfil_controller.rb
class PerfilController < ApplicationController
  def index
  end
end

app/helpers/perfil_helper.rb
module PerfilHelper
end

app/views/perfil/index.html.erb
<br>
<div class="row per">
  <div class="large-4 large.centred columns"><h5 class="perfil">Perfil</h5></div>
</div>
<div class="row perf">
  <br>
  <div class="large-7 large-offset-5 small-8 small-offset-4 columns columns"><%= image_tag current_user.avatar,class:"avatar"%></div>
  <br>
</div>
<div class="row perf">
  <div class="large-7 large-offset-5 small-8 small-offset-4 columns columns"><strong class="perfil" style="text-transform: uppercase;"><%= current_user.name%> </strong></div>
</div>
<div class="row perf">
  <div class="large-7 large-offset-5 small-8 small-offset-4 columns columns"><strong class="perfil"><%= current_user.rol%> </strong></div>
</div>
<br>
<div class="row">
  <div class="large-4 large-offset-2 small-9 small-offset-3 columns"><%=link_to "Editar perfil", edit_user_registration_path,class:'button'%></div>
  <div class="large-4 large-offset-2 small-9 small-offset-3 columns"><%= link_to "Cerrar sesíon", destroy_user_session_path, method: :delete,class:'button'%></div>
</div>

<%if current_user.rol=="administrador"%>
<%= link_to 'Administrar sitio', rails_admin_path %>
<%end%>