config/routes.rb
Rails.application.routes.draw do
  get 'archivos/subir_archivos'
  post 'archivos/subir_archivos'
  get 'archivos/listar_archivos'
  post 'archivos/borrar_archivos'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
    }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "perfil#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "MusicForAll" %></title>
    <link rel="icon" type="image/png" href="/assets/icon.png">

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <% unless flash.empty? %>
    <script type="text/javascript">
      <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
      toastr['<%= type %>']('<%= f[1] %>');
             <% end %>
    </script>
    <% end %>

    <%if user_signed_in?%>
    <div class="row">
      <div class="small-12 medium-8 medium-offset-2 columns">
        <div class="contain-to-grid">
          <nav class="top-bar" data-topbar>
            <ul class="title-area">
              <li class="name">
                <h1><a href="#">MusicForAll</a></h1>
              </li>
              <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
            </ul>
            <section class="top-bar-section">
              <!-- Right Nav Section -->
              <%if user_signed_in? and current_user.rol=="contribuidor" or current_user.rol=="administrador"%>
              <ul class="right">
                <li><a href="/"><%= image_tag current_user.avatar,class:"avatarx"%> <%= current_user.name %> <a></li>
                  <li class="has-dropdown">
                    <a href="#">Musica</a>
                    <ul class="dropdown">
                      <li><%= link_to 'Subir cancion', archivos_subir_archivos_path %></li>
                      <li><%= link_to 'Lista de canciones', archivos_listar_archivos_path %></li>
                    </ul>
                  </li>
                  </ul>
                  <%end%>
                  <%if user_signed_in? and current_user.rol=="suscriptor"%>
                  <ul class="right">
                    <li><a href="/"><%= image_tag current_user.avatar,class:"avatarx"%> <%= current_user.name %> <a></li>
                      <li class="has-dropdown">
                        <a href="#">Musica</a>
                        <ul class="dropdown">
                          <li><%= link_to 'Lista de canciones', archivos_listar_archivos_path %></li>
                        </ul>
                      </li>
                      </ul>
                      <%end%>
                      <%else%>
                      <%end%>
                    </section>
                </nav>
              </div>
            </div>
        </div>

        <%= yield %>
        <%= javascript_include_tag "application" %>
        </body>
      </html>